config/routes.rb
Rails.application.routes.draw do
    root 'messages#index'
    resources :users
    devise_for :users, :path_prefix => 'd'
    get 'users/:id' => 'users#show'

    resources :messages do
        resources :comments
    end
    resources :cities do
      :games
    end
     resources :games

     resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :games
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :messages
  belongs_to :user
  belongs_to :city
end

app/models/message.rb
class Message < ApplicationRecord
  
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :comments

  has_many :games

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :exception

    before_filter :initialize_message

    protected

    def configure_permitted_parameters
        added_attrs = [:city_id, :username, :email, :password, :password_confirmation, :remember_me]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

    def initialize_message
        @message = Message.new
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    city_id = params[:id]
    @city = City.find_by_id(city_id)
  end

  def new
    @city = City.new
  end

  def create
    city_params = params.require(:city).permit(:name, :location)
    city = City.new(city_params)
    if city.save
      redirect_to cities_path(city)
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_message
  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

 def create

   @comment = @message.comments.create(comment_params)
   @comment.user_id = current_user.id

    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
 end

 def edit
 end

 def update
   if @comment.update(comment_params)
     redirect_to message_path(@message)
   else
     render 'edit'
   end
 end

 def destroy
   @comment.destroy
   redirect_to message_path(@message)
 end

 private

 def comment_params
   params.require(:comment).permit(:content)
 end

 def find_message
   @message = Message.find(params[:message_id])
 end

 def find_comment
   @comment = @message.comments.find(params[:id])
 end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
    def index
      @messages = Message.all.order("created_at DESC")
    end

    def show

    end

    def new
        @messsage = current_user.messages.build
    end

    def create
        @message = current_user.messages.build(message_params)
        if @message.save
          redirect_to root_path
        else
          flash[:error] = @message.errors.full_messages.join(", ")
          render 'new'
        end
    end

def edit

end

def update
  if @message.update(message_params)
    redirect_to message_path
  else
    render 'edit'
  end
end

def destroy
  @message.destroy
  redirect_to root_path
end

    private

    def message_params
        params.require(:message).permit(:title, :description)
    end

    def find_message
      @message = Message.find(params[:id])
    end
end

app/controllers/users_controller.rb
#Help! Auth is broken in production
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
  end

    def index
        @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/cities/create.html.erb
<%= simple_form_for @city do |f| %>
	<%= f.input :name, label: "City Name" %>
	<%= f.input :location %>
	<%= f.button :submit %>
<% end %>

app/views/cities/destroy.html.erb
<h1>Cities#destroy</h1>
<p>Find me in app/views/cities/destroy.html.erb</p>

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/new.html.erb
<div class="form-group row">
  <%= form_for :city, url: "/cities", method: "post" do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :location %>
  <%= f.submit "Save City", class: "btn btn-custom" %>
<% end %>
</div>

app/views/cities/show.html.erb
<h3><%= @city.name %></h3>
<p><%=  @city.location %></p>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/comments/_comment.html.erb
<div class="comment">
    <p class="comment-content"><%= comment.content %></p>
    <p class="comment-posted-by">Posted by
        <%= link_to " #{comment.user.username}", comment.user %></span>
        <%= time_ago_in_words(comment.created_at) %>
        ago</p>




    <div class="links">
        <% if user_signed_in? %>
        <% if comment.user_id == current_user.id %>
        <%= link_to"Edit", edit_message_comment_path(comment.message, comment) %>

        <%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Are you sure?"} %>
        <% end %>
        <% end %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
<%= f.input :content, label: "Comment" %>
<%= f.button :submit, :class => 'btn-custom' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= simple_form_for([@message, @comment]) do |f| %>
 <%= f.input :content, label: "Comment" %>
 <%= f.button :submit %>
<% end %>

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/destroy.html.erb
<h1>Games#destroy</h1>
<p>Find me in app/views/games/destroy.html.erb</p>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/edit.html.erb</p>

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nerds of Play</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Nerds of Play", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <% if user_signed_in? %>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
          <li>
            <%= link_to " #{current_user.username}", current_user %>
          </li>
          <% else %>
          <li>
            <%= link_to "Log In", new_user_session_path %>
          </li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
        <p>
          <%= link_to " New Post", new_message_path, method: :get, class: "navbar-right navbar-text navbar-link" %>
        </p>
        <% end %>
      </div>
    </div>
    <p class="notice">
      <%= notice %>
    </p>
    <p class="alert">
      <%= alert %>
    </p>
    <%- flash.each do |name, msg| -%>
      <div class="alert alert-warning">
        <strong><%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %></strong>
      </div>
    <%- end -%>
    <div class="col-md-8 col-md-offset-2">
      <!--It is confusing that this is a link to the root path, which we are already on....maybe make it just and h1 -->
                            <h1 class="quest"><%= link_to "Ready to Quest?", root_path %></h1>
                          </div>
    <div class="container">
		<%= yield %>
	</div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
	<%= f.input :title, label: "Message Title" %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
	<div class="col-md-6">
		<div class="message">
			<h2 class="message-title"><%= message.title %></h2>
			<%= link_to "View Message", message, class: "btn-custom" %>
		</div>
	</div>
<% end %>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1 class="new-msg-header">New Message</h1>
	<%= render 'form' %>
</div>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2">
    <div class="message-show">
        <h2>
            <%= @message.title %></h2>
        <p class="message-posted-by">
            Posted by:
            <%= @message.user.username %>
            <%= time_ago_in_words(@message.created_at) %>
            ago
        </p>
        <p class="message-desc">
            <%= @message.description %>
        </p>
        <h3 class="comment-section-header">Comments:</h3>
        <%= render @message.comments %>

        <h3 class="reply-to-msg">Reply to Message:</h3>
        <%= render 'comments/form' %>

        <div class="links btn-group">
            <%= link_to 'Back', root_path, class: "btn btn-default" %>
            <% if user_signed_in? %>
            <% if @message.user_id == current_user.id %>
            <%= link_to "Edit", edit_message_path(@message), class: "btn btn-default" %>
            <%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default" %>
            <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% @users = User.all %>
<% @users.each do |user| %>
  <%= user.username %><br/>
  <%= user.email %><br/>
<% end %>

app/views/users/show.html.erb
<body>
    <div class="team-boxed">
        <div class="container">
            <div class="row people">
                <div class="col-md-4 col-sm-6 item">
                    <div class="box"><img src="1.jpg" class="img-circle"/>

                        <% if current_user != @user %>
                        <h3 class="name"><% user_path %></h3>
                        <% end %>
                        <p class="title"><%= @user.username %></p>
                        <p class="description"><%= @user.email %></p>
                        <% if @user == current_user %>
                        <p><%= link_to "Edit Profile", edit_user_registration_path %></p>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>